default:examplescfd examplesgfd

examplescfd:
	/usr/bin/pdflatex examples_CFD
	/usr/bin/pdflatex examples_CFD
        
examplesgfd:
	/usr/bin/pdflatex examples_GFD
	/usr/bin/pdflatex examples_GFD
        
clean:
	rm *.aux *.log *.nav *.out *.snm *.toc
