plot:
	echo "plot for elmin"
	pdflatex pgfplot_texfile_st-andrews-cross_fsi_results_elmin.tex
	pdflatex pgfplot_texfile_st-andrews-cross_fsi_results_elmin.tex
	pdfcrop pgfplot_texfile_st-andrews-cross_fsi_results_elmin.pdf pgfplot_texfile_st-andrews-cross_fsi_results_elmin.pdf
	echo "plot for degrees of freedom"
	pdflatex pgfplot_texfile_st-andrews-cross_fsi_results_numnodes.tex
	pdflatex pgfplot_texfile_st-andrews-cross_fsi_results_numnodes.tex
	pdfcrop pgfplot_texfile_st-andrews-cross_fsi_results_numnodes.pdf pgfplot_texfile_st-andrews-cross_fsi_results_numnodes.pdf
	
